# Site settings
title: Tocaki
email: contato@tocaki.net
description: >
  Pumpkin spice black, french press bar seasonal id coffee.
  Whipped carajillo french press doppio at latte extra half
  and half roast aftertaste grinder aftertaste.
baseurl: ""
url: "http://tocaki.net"
facebook: tocakinet
instagram: tocakinet
blogurl: ""
subscriptionurl: ""

# Build settings
markdown: kramdown
permalink: pretty
collections:
  artists:
    output: true
    permalink: /:path/
  genres:
    output: false
defaults:
  -
    scope:
      path: ""
      type: artists
    values:
      layout: profile

# Prose
prose:
  ignore:
    - /_layouts
    - /_includes
  metadata:
    _artists:
      - name: name
        field:
          element: text
          label: Nome
      - name: city
        field:
          element: text
          label: Cidade
      - name: type
        field:
          element: select
          label: Tipo
          options:
            - Banda
            - Solo
      - name: genre
        field:
          element: text
          label: Gênero
      - name: portfolio
        field:
          element: text
          label: Portfólio
      - name: email
        field:
          element: text
          label: E-mail
      - name: phone
        field:
          element: text
          label: Telefone
          help: Opcional
      - name: facebook
        field:
          element: text
          label: Nome de usuário do Facebook
          help: Opcional
      - name: twitter
        field:
          element: text
          label: Nome de usuário do Twitter
          help: Opcional
      - name: gplus
        field:
          element: text
          label: Nome de usuário do Google+
          help: Opcional
