# Site settings
title: Tocaki
email: contato@tocaki.net
description: >
  Pumpkin spice black, french press bar seasonal id coffee.
  Whipped carajillo french press doppio at latte extra half
  and half roast aftertaste grinder aftertaste.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tocaki.net"

# Build settings
markdown: kramdown
permalink: pretty
collections:
  artists:
    output: true
    permalink: /:path/
