# Site settings
title: Tocaki
email: contato@tocaki.net
description: >
  Pumpkin spice black, french press bar seasonal id coffee.
  Whipped carajillo french press doppio at latte extra half
  and half roast aftertaste grinder aftertaste.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tocaki.net"
beta_form: "https://docs.google.com/forms/d/e/1FAIpQLSdrNreMphVy_nOVFNE4QNqTusiSQwP4Ch7VWtcj6z7pA4I3wQ/viewform?c=0&w=1"

# Build settings
markdown: kramdown
permalink: pretty
